### ISSUE TITLE
variants compilation not working as intended

### ISSUE THREAD

**Issue by preslavgerchev** [mondoohq/cnspec#1256]
**Describe the bug**
Trying to scan with the following bundle file fails:
```
policies:
  - uid: example1
    name: Example policy 1
    version: 1.0.0
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - filters: asset.family.contains('unix')
        checks:
          - uid: test-v
            variants:
              - uid: test
          - uid: test
            filters: asset.family.contains('unix')
            mql: 2 > 1
```

```
cnspec scan -f bundle.yaml
```

**Expected behavior**
I would expect that this policy is compiled and variants are transformed properly
