### ISSUE TITLE
compliance framework does not render data queries in Mondoo Platform

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#1320]
**Describe the bug**
Compliance frameworks should be able to be edited with data queries to collect evidence (validated by @arlimus and @tas50 ). I downloaded the SOC 2 framework and added data queries to that policy but they did not render in Mondoo Platform. The following snippet updates CC6.1.1 and can be used for testing.

```
      - uid: soc2-group-cc6-1
        title: CC6.1 - The entity implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security events to meet the entity’s objectives
        controls:
          - uid: soc2-control-cc6-1-1
            title: 'CC6.1.1: Identifies and Manages the Inventory of Information Assets'
            docs:
              desc: |
                ### SSH keys are utilized to prevent unauthorized access to production infrastructure.

                Marcum request: Provide the following: 

                1. SSH keys implementation/configuration evidence for EC2 access
                2. List of users and groups in AWS IAM
            evidence:
              - uid: soc2-2017-mondoo-soc2-inventory-mapping
                queries:
                  # - mrn: //policy.api.mondoo.app/queries/mondoo-compliance-inventory-asset-data
                  - uid: lunalectric-soc2-6-1-1-aws-iam-users
                    title: List of users groups in AWS IAM
                    filter: asset.platform == "aws"
                    mql: |
                      aws.account.id
                      aws.iam.users
                  - uid: lunalectric-soc2-6-1-1-aws-ec2-ssh-keypairs
                    title: SSH keys implementation/configuration evidence for EC2 access
                    filter: asset.platform == "aws"
                    mql: |
                      aws.account.id
                      aws.ec2.keypairs
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**
