### ISSUE TITLE
Removing old resolver breaks output with different formats

### ISSUE THREAD

**Issue by slntopp** [mondoohq/cnspec#1540]
**Describe the bug**
After this commit https://github.com/mondoohq/cnspec/commit/f5aaceb517fccfd59cdf0ba22d0ddc3b0d6dbbee was introduced we aren't getting any data in the reports. Running the scan without `--output` shows that data queries are executed and collected correctly

**To Reproduce**

Create `bundle.mql.yaml` like:

```yaml
packs:
- uid: sbom
  name: SBOM
  filters:
  - mql: asset.family.contains("unix")
  - mql: asset.family.contains("windows")
  queries:
  - uid: sbom-asset
    title: Retrieve information about the Platform
    mql: asset { name platform version arch ids labels cpes.map(uri) }
  - uid: sbom-packages
    title: Retrieve list of installed packages
    mql: packages { name version purl cpes.map(uri) format }
  - uid: sbom-python-packages
    title: Retrieve list of installed Python packages
    mql: python.packages { name version purl cpes.map(uri) file.path }
  - uid: sbom-npm-packages
    title: Retrieve list of installed npm packages
    mql: npm.packages { name version purl cpes.map(uri) files.map(path) }
```

Run a scan with this, local or otherwise

```shell
cnspec scan local -f bundle.mql.yaml
```
This will return truncated output with packages list in the data queries section

Re-run the scan with `--output`:
```shell
cnspec scan local -f bundle.mql.yaml --output yaml
# or
cnspec scan local -f bundle.mql.yaml --output json
```

This will results into something like:
```yaml
***
data:
  //policy.api.mondoo.com/assets/asset-id: {}
***
```
