### ISSUE TITLE
props on a global level are not working

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnspec#1579]
i defined a new new global prop and if i run a cnspec policy lint, i get the following message:

```bash
cnspec policy lint examples/props.mql.yaml
→ lint policy bundle file=examples/props.mql.yaml
  RULE ID               LEVEL  FILE            LINE  MESSAGE
  bundle-compile-error  error  props.mql.yaml  1     could not compile policy bundle:failed to validate query
                                                     '//local.cnspec.io/run/local-execution/queries/check-4':
                                                     failed to compile query 'props.adminaccount + " on 4"':
                                                     cannot find property 'adminaccount', please define it
                                                     first
FTL invalid policy bundle
```

here my example policy 

[props.mql.yaml.zip](https://github.com/user-attachments/files/18849170/props.mql.yaml.zip)

**Comment by vjeffrey** [comment]
@jaym can you help us with this? @atomic111 needs this for a policy he is writing and it appears that this is more than just a linting issue - we are not reading the global props from the query context

**Comment by jaym** [comment]
yes, maybe @glower and I can pair on it on monday

**Comment by jaym** [comment]
@atomic111 I see you use the for section in props, but looking through the code that doesn't do anything

**Comment by jaym** [comment]
requires https://github.com/mondoohq/server/pull/11078

**Comment by jaym** [comment]
also requires https://github.com/mondoohq/cnspec/pull/1631

**Comment by vjeffrey** [comment]
should now work with:
```
policies:
  - uid: example1
    name: Example policy 1
    version: "1.0.0"
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - title: group1
        filters: asset.family.contains("unix")
        checks:
          - uid: check-4
    props:
      - uid: adminaccount
        mql: return "adminaccount"

queries:
  - uid: check-4
    title: check 4
    mql: props.adminaccount == "foo"
    filters: asset.family.contains("unix")
    props:
      - uid: adminaccount
```

on latest cnspec

**Comment by atomic111** [comment]
@jaym and @vjeffrey i test it with the following policy:

```yaml
# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# This bundle contains two policies
policies:
  - uid: example1
    name: Example policy 1
    version: "1.0.0"
    authors:
      - name: Mondoo
        email: hello@mondoo.com
    groups:
      - title: group1
        filters: asset.family.contains("unix")
        queries:
          - uid: variant-check
          - uid: check-4
    props:
      - uid: userHome
        for:
          - uid: home
          - uid: homeDir
        mql: return "ex"
      - uid: adminaccount-check
        for:
          - uid: adminaccount
        mql: return "admin account"

queries:
  - uid: variant-check
    title: Variant check
    variants:
      - uid: variant-1
      - uid: variant-2
      - uid: variant-3

  - uid: variant-1
    mql: props.home + " on 1"
    filters: asset.family.contains("unix")
    props:
      - uid: home
        mql: return "p1"

  - uid: variant-2
    mql: props.home + " on 2"
    filters: asset.family.contains("unix")
    props:
      - uid: home
        mql: return "p2"

  - uid: variant-3
    mql: props.homeDir + " on 3"
    filters: asset.family.contains("unix")
    props:
      - uid: homeDir
        mql: return "p3"

  - uid: check-4
    mql: props.adminaccount + " on 4"
````

i use the cnspec v11.54.0 (852926b, unknown). i still have the lint problem:

```
cnspec policy lint props.mql.yaml
→ lint policy bundle file=props.mql.yaml
x provider without schema, unable to look up dependencies provider=core
  RULE ID               LEVEL  FILE            LINE  MESSAGE
  bundle-compile-error  error  props.mql.yaml  1     could not compile policy bundle:failed to validate query
                                                     '//local.cnspec.io/run/local-execution/queries/check-4':
                                                     failed to compile query 'props.adminaccount + " on 4"':
                                                     cannot find property 'adminaccount', please define it
                                                     first
  query-name            error  props.mql.yaml  58    query check-4 does not define
                                                     a title
FTL invalid policy bundle
```

then i execute the policy and it does not execute my check-4

```
cnspec scan -f ./props.mql.yaml
→ Connecting to your local system. To learn how to scan other platforms, use the --help flag.
→ loaded configuration from /Users/atomic111/.config/mondoo/mondoo.yml using source default
→ using service account credentials
! Scanning with local bundles will switch into --incognito mode by default. Your results will not be sent upstream.
→ discover related assets for 1 asset(s)

 atomic111 ─────────────────────────────────────────────────────────────────────────────────────────  n/a score: UNRATED


Asset: (macOS) atomic111
------------------------

Data queries:
home.+: "ex on 1"



Scanned 1 asset

macOS
    [0/100]     atomic111
```

also for the variant check i was expecting the following output:

```
p1 on 1
```

Why: The prop that is defined in the query itself should overwrite the global defined prop.

Problem summary:

1. Policy lint is not working
2. Policy execution does not execute my check-4
3. same prop is defined on check level should overwrite the global defined prop
