### ISSUE TITLE
add group uid check to linter for policies

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnspec#1583]
to prevent folks from writing policies like:
```
    groups:
      - title: Core Checks
        checks: 
          - uid: core-gcp-cloud-sql-private-ip-check
          - uid: core-gcp-cloud-sql-deletion-protection-enabled
      - title: Cost Efficiency
        checks: 
          - uid: core-gcp-cloud-sql-availability-non-prod
```

where the groups do not have uids
