### ISSUE TITLE
ansible-inventory, ipv6 and brackets

### ISSUE THREAD

**Issue by micheelengronne** [mondoohq/cnspec#403]
**Describe the bug**
When using ipv6 in an anisble inventory we are forced to write them without brackets because SSH does not support them.

When we want to reuse the inventory file with cnspec, it complains "Error: “dial tcp: address 2601:547:980:b3e0::677c:32774: too many colons in address"

**To Reproduce**

* Create an ansible inventory file with ipv6 addresses without brackets
* Use this inventory file with cnspec

**Expected behavior**
cnspec should detect the use of ipv6 and add the brackets automatically.

**Comment by micheelengronne** [comment]
As a workaround, as I generate my inventory-files automatically I create a variant for ansible and one for cnspec.

**Comment by chris-rock** [comment]
@micheelengronne can you share sample entry of the ansible inventory and then how you convert it? To you use cnspec `--inventory-file`?

**Comment by micheelengronne** [comment]
I use:

```
ansible-inventory -i inventory.yml --list > hosts.json
cnspec scan \
  --inventory-file hosts.json \
  --inventory-ansible \
  --insecure \
  --incognito \
  --policy-bundle cnspec.yaml \
  --detect-cicd=true \
  --output full
```

with this inventory file:

```
all:
  children:
    wg_nodes:
      hosts:
        wg-1:
          ansible_host: 'fc00:fc00:fc00:fc00:fc01:fc01:fc01:1'
          ansible_user: root
          ansible_ssh_private_key_file: id_ed25519
        wg-2:
          ansible_host: 'fc00:fc00:fc00:fc00:fc01:fc01:fc01:2'
          ansible_user: root
          ansible_ssh_private_key_file: id_ed25519
        wg-3:
          ansible_host: 'fc00:fc00:fc00:fc00:fc01:fc01:fc01:3'
          ansible_user: root
          ansible_ssh_private_key_file: id_ed25519
```
