### ISSUE TITLE
cnspec bundle format should update `scoring_system`

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#448]
**Is your feature request related to a problem? Please describe.**
Right now you can define `scoring_system` in a policy with a number or the friendly value. When we run `cnspec bundle format` on a policy we should write out the friendly format, which is much more newcomer friendly.

**Describe the solution you'd like**
Give

```yaml
policies:
  - uid: example1
    name: Example policy 1
    version: "1.0.0"
    scoring_system: 2
```

Running `cnspec bundle format example.yml` would result in:

```yaml
policies:
  - uid: example1
    name: Example policy 1
    version: "1.0.0"
    scoring_system: highest impact
```
