### ISSUE TITLE
data queries in cnspec policies with variants are show up as skipped

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#527]
**Describe the bug**
Working with @arlimus  on adding data queries to policies that leverage variants. When executing the policy, the data queries are skipped. 

For example, if I add the following data query to a cnspec policy for GCP

```
  - uid: gcp-bigquery-data-gather
    title: gather data about BigQuery
    filters: |
      asset.platform == "gcp" || asset.platform == "gcp-project"
      asset.kind == "api" || asset.kind == "gcp-object"
    mql: gcp.project.bigquery.datasets {*} 
  ```

When the policy is executed against a GCP project, the data query is skipped...

```
Controls:
✓ Pass:  A 100  Ensure instances are not configured to use the default service account with full access to all Cloud APIs
✓ Pass:  A 100  Ensure that Cloud Storage buckets are not anonymously or publicly accessible
✓ Pass:  A 100  Ensure oslogin is enabled for compute instances
✓ Pass:  A 100  Ensure That BigQuery Datasets Are Not Anonymously or Publicly Accessible
✕ Fail:  C  40  Ensure that Cloud Storage buckets have uniform bucket-level access enabled
✓ Pass:  A 100  Ensure "Block Project-wide SSH keys" is enabled for VM instances
✓ Pass:  A 100  Ensure Google Cloud Storage buckets are configured with uniform bucket level access
✓ Pass:  A 100  Ensure that instances are not configured to use the default service account
. Skipped: gather data about BigQuery
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by scottford-io** [comment]
The issue is the data query was being called under the `checks` section of the policy and it needs to be called under a `queries` section instead...

## Incorrect example - data query being called under `checks`

```
      - title: GCP BigQuery
        checks:
          - uid: gcp-security-bigquery-no-public-access
          - uid: gcp-bigquery-data-gather # <------ THIS IS WRONG
 ```

## Correct example - data query being called under `queries`

Data queries need to be called under a `queries` section as follows...

```
    groups:
      - title: GCP BigQuery
        checks:
          - uid: gcp-security-bigquery-no-public-access
        queries:
          - uid: gcp-bigquery-data-gather
 ```
