### ISSUE TITLE
Data queries in cnspec policies do not populate the resources explorer

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#528]
**Describe the bug**
cnspec policies that leverage data queries are sending data back to the console, but that data does not end up in the resources explorer.

## Example of data query in policy

```
# DATA QUERIES
  - uid: gcp-bigquery-data-gather
    title: gather data about BigQuery
    filters: |
      asset.platform == "gcp" || asset.platform == "gcp-project"
      asset.kind == "api" || asset.kind == "gcp-object"
    mql: gcp.project.bigquery.datasets {*}  
```

## The query above is called in a cnspec policy as follows:

```
    groups:
      - title: GCP BigQuery
        checks:
          - uid: gcp-security-bigquery-no-public-access
        queries:
          - uid: gcp-bigquery-data-gather
  ```

## Example - data query results in Mondoo Platform

When the policy is executed, results show up in the console as follows:

![image](https://user-images.githubusercontent.com/49754039/233730738-232ab484-0511-45ca-b9f7-1d1dcbb7b84b.png)

## Example - Data queries do not populate the resources explorer

![image](https://user-images.githubusercontent.com/49754039/233730888-b25a3616-edc8-4106-acac-aa1480cbad43.png)

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**
