### ISSUE TITLE
`gcp.project.gke.clusters.all` doesn't display default values

### ISSUE THREAD

**Issue by multani** [mondoohq/cnspec#532]
**Describe the bug**

`gcp.project.gke.clusters.all` doesn't seem to display default values.

Apparently, [`name` is the default value for GKE cluster resources](https://github.com/mondoohq/cnquery/blob/c5d87f33a5335b1f83eba7c00b082ef2e5b59742/resources/packs/gcp/gcp.lr#L1404), but when `.all()` fails, it doesn't display the name.

**To Reproduce**

I have a check written as follow:

```yaml
          - uid: gke-01
            title: Ensure that etcd database is encrypted
            mql: gcp.project.gke.clusters.all( databaseEncryption["state"] == "ENCRYPTED" )
```

It currently fails with the following output:

```
Controls:
✕ Fail:  Ensure that etcd database is encrypted
  Query:

  Result:
    [failed] [].all()
      actual:   [
        0: gcp.project.gkeService.cluster id = gcp.project.gkeService.cluster/7c50e440aa5c41cf8eff749a4f313953c4c974b985ab43d1b44871e7dbf3e9a7
        1: gcp.project.gkeService.cluster id = gcp.project.gkeService.cluster/db3328e173c84de49d92229c02378c9f59b69e0a568a4448b52b3d7ff2f201f6
      ]
```

It's difficult to see from the output which GKE clusters are actually misconfigured.

**Expected behavior**

I expect to see, at least, the name of the GKE cluster, as reported by the `gcp.project.gke.clusters` query.

**Screenshots or CLI Output**

See above

**Desktop (please complete the following information):**

```
$ cnspec version                                                      
cnspec 8.6.0 (d8cf5a8, 2023-04-18T17:26:39Z)
```

**Additional context**
