### ISSUE TITLE
Prettify Errors for Users that don't lint their code

### ISSUE THREAD

**Issue by kmf** [mondoohq/cnspec#564]
Faulty Code:  (ref `rhel` instead of `centos`)

```
policies:
    - uid: greetings
      name: Another policy
      version: "1.0.0"
      groups:
      - checks:
        - uid: hello-os
          variants: 
          - uid: ubuntu
          - uid: rhel


queries:
  - uid: ubuntu
    title: Hello Ubuntu
    mql: platform.name == 'ubuntu'
    filters: platform.name == 'ubuntu'

  - uid: centos
    title: Hello Centos
    mql: platform.name == 'centos'
    filters: platform.name == 'centos'
```

```
❯ cnspec scan ssh user@host --identity-file=/Users/user/.ssh/id_rsa -f test.mql.yml
→ loaded configuration from /Users/user/.config/mondoo/mondoo.yml using source default
→ using service account credentials
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x80 pc=0x10a9c1054]

goroutine 1 [running]:
go.mondoo.com/cnspec/policy.(*bundleCache).ensureNoCyclesInVariants(0x140019bfaa8?, {0x14000223e00, 0x1, 0x87804cce4fb0cda0?})
	/home/runner/_work/cnspec/cnspec/policy/bundle.go:520 +0x84
go.mondoo.com/cnspec/policy.(*bundleCache).compileQueries(0x140019bfaa8, {0x140010e2840, 0x1, 0x9?}, 0x2?)
	/home/runner/_work/cnspec/cnspec/policy/bundle.go:753 +0xc0
go.mondoo.com/cnspec/policy.(*Bundle).Compile(0x140006bcb40, {0x10d9771b0, 0x14000218000}, {0x0?, 0x0})
	/home/runner/_work/cnspec/cnspec/policy/bundle.go:687 +0x868
go.mondoo.com/cnspec/apps/cnspec/cmd.(*scanConfig).loadPolicies(0x14001d27680)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:614 +0x64
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func22(0x0?, {0x14001d004c0?, 0x0?, 0x0?}, 0x0?, 0x0?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:384 +0x70
go.mondoo.com/cnquery/apps/cnquery/cmd/builder.sshProviderCmd.func1(0x1400185d800?, {0x14001d004c0?, 0x4?, 0x4?})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230509085527-5e7aee4980b4/apps/cnquery/cmd/builder/builder.go:229 +0x30
github.com/spf13/cobra.(*Command).execute(0x1400185d800, {0x14001d00480, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x111fd88c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:80 +0x28
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:6 +0x1c

```

Working Code produces no error

```
policies:
    - uid: greetings
      name: Another policy
      version: "1.0.0"
      groups:
      - checks:
        - uid: hello-os
          variants: 
          - uid: ubuntu
          - uid: centos


queries:
  - uid: ubuntu
    title: Hello Ubuntu
    mql: platform.name == 'ubuntu'
    filters: platform.name == 'ubuntu'

  - uid: centos
    title: Hello Centos
    mql: platform.name == 'centos'
    filters: platform.name == 'centos'
```
