### ISSUE TITLE
Targeting a specific k8s cluster with `--context` doesnt seem to work

### ISSUE THREAD

**Issue by mariuskimmina** [mondoohq/cnspec#593]
**Describe the bug**
I have 2 k8s clusters in my `~/.kube/config` 

```
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 31 Oct 2022 07:23:38 CET
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
- context:
    cluster: kind-my-test-cluster
    user: kind-my-test-cluster
  name: kind-my-test-cluster
current-context: kind-my-test-cluster
```

One being `minikube` the other being `kind-my-test-cluster`. 

`kind-my-test-cluster` is the default cluster - the `current-context` thus running `cnspec scan k8s` is scanning `kind-my-test-cluster`. 
When I try to specify a `context` with `cnspec scan k8s --context minikube` it still scans `kind-my-test-cluster`. 

Am I missunderstanding something, or does the `--context` flag not work?

**To Reproduce**

1. Have 2 clusters in your kube config
2. Try to target the non-default one with `--context`

**Expected behavior**
I expected it to scan my minikube cluster when using `--context minikube`

**Screenshots or CLI Output**
```
/cnspec scan k8s --context minikube
→ no Mondoo configuration file provided. using defaults
→ discover related assets for 1 asset(s)
→ discovery option auto is used. This will detect the assets: cluster, cronjobs, daemonsets, deployments, ingresses, jobs, pods, replicasets, statefulsets
→ use cluster name from kube config cluster-name=kind-my-test-cluster
→ resolved assets resolved-assets=23

...
```

**Desktop (please complete the following information):**
- OS: PopOS
- OS Version: 22.04
