### ISSUE TITLE
"failed to find where function for assessment" error message

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#618]
**Describe the bug**

I have a simple policy like:

```
policies:
  - uid: policy-1
    name: My Custom Policy
    version: 1.0.0
    groups:
      - title: 'Careful Allocation of IDs'
        filters: |
          platform.family.contains(_ == 'linux')
        checks:
          - uid: check-1
queries:
  - uid: check-1
    title: Ensure no duplicate UIDs exist
    mql: |
      users.list.duplicates(uid).none()
```

Then I gather the following output:

```bash
cnspec scan docker debian:11 -f ./stable/policy1.mql.yaml
→ loaded configuration from /Users/chris/.config/mondoo/mondoo.yml using source default
→ using service account credentials
x failed to find where function for assessment
x failed to find where function for assessment
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1

 debian:11@cd608ff13449 ━━━━━━━━━ 100% score: A


x failed to find where function for assessment
x failed to find where function for assessment
x failed to find where function for assessment
Asset: debian:11@cd608ff13449
-----------------------------

Checks:
✓ Pass:         Ensure no duplicate UIDs exist
```

It prints multiple errors `x failed to find where function for assessment`. The issue was introduced in https://github.com/mondoohq/cnquery/pull/1219

**To Reproduce**

Run the following command with the policy mentioned above.

```bash
cnspec scan docker debian:11 -f ./stable/policy1.mql.yaml
```

**Expected behavior**

No error message

**Screenshots or CLI Output**

see above

**Desktop (please complete the following information):**

n/a

**Additional context**

n/a
