### ISSUE TITLE
migrate inventory.yml to new format

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#793]
**Is your feature request related to a problem? Please describe.**

As reported in https://github.com/mondoohq/cnspec/issues/788, customers may use custom inventory.yml files like:

```yaml
apiVersion: v1
kind: Inventory
metadata:
  name: mondoo-inventory
  labels:
    environment: production
spec:
  assets:
    - id: test
      connections:
        - backend: local
```

This outputs an warning that `backend` should be switched to `type`. Since we have a `cnspec migrate` command, I think this should upgrade the inventory config to latest and greatest, so that the user does not need to worry about it.

**Describe the solution you'd like**

Extend the behaviour for `cnspec migrate` so that it loads inventories, and switches the config from `backend` to `type`

**Describe alternatives you've considered**

none
