### ISSUE TITLE
Extend query/check scope decentrally

### ISSUE THREAD

**Issue by arlimus** [mondoohq/cnspec#954]
tbd - placeholder

kudos @JosiahOne

**Comment by scottford-io** [comment]
@arlimus I assume that docs and remediation steps would work the same in that you can have individual steps with each child variant? 

```
queries:
- uid: aws-ssh-check
  extends: cloud-ssh-check
  filters: ...
  mql: ...
  docs:
    remediation:
      - id: console
        desc: |
          # Markdown goes here
           
          1. Step 1
          2. Step 2
          3. etc
```
