### ISSUE TITLE
Data query variants don't have reporting jobs

### ISSUE THREAD

**Issue by preslavgerchev** [mondoohq/cnspec#970]
**Describe the bug**
This may be intentional (in which case this is a feature request) but data query variants do not have reporting jobs on their own in the resolved policy. This makes it hard to keep track of what data query has run (either by code ir or mrn) since those jobs get converted to datapoints and then get deleted
A sample query pack with variants to reproduce:
```
packs:
- uid: pack1
  groups:
  - type: chapter
    filters: "true"
    queries:
    - uid: query1
queries:
- uid: query1
  variants:
  - uid: query2
  - uid: query3
- uid: query2
  title: query2
  filters: "true"
  mql: asset.version
- uid: query3
  title: query3
  filters: "false"
  mql: asset.platform
```

Run ` DEBUG=1 cnspec scan -f packs.yaml` and inspect the resolved policy. There are no reporting jobs for `query2` and `query1`. This works as expected with *checks*

**Expected behavior**
That data queries have reporting jobs too. That makes it easier to keep track of what data query has been executed.
